server:
  port: ${PORT:8080} 

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false 

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-1.5-flash 

resilience4j:
  circuitbreaker:
    instances:
      targetApi: 
        slidingWindowSize: 5 
        failureRateThreshold: 50 
        waitDurationInOpenState: 15s 
        permittedNumberOfCallsInHalfOpenState: 2 
        minimumNumberOfCalls: 3